import React,{useMemo,useState} from 'react';
import {cx} from '../../utils/cx';
import './advanced-datatable.scss';

export type AdvancedColumn<T>={key:string;header:React.ReactNode;accessor?:(row:T)=>React.ReactNode;value?:(row:T)=>unknown;editable?:boolean;sticky?:'left'|'right';width?:number;minWidth?:number};
export type TableView={id:string;name:string;filters:Record<string,string>;density?:'compact'|'normal'|'comfortable'};
export function AdvancedDataTable<T>({data,columns,rowKey,childrenOf,onChangeCell,onPageChange,page=1,pageSize=10,total,serverSide=false,onFilter,views=[],onSaveView,onExport,renderExpanded}:{data:T[];columns:AdvancedColumn<T>[];rowKey:(row:T)=>string;childrenOf?:(row:T)=>T[]|undefined;onChangeCell?:(row:T,key:string,value:string)=>void;onPageChange?:(page:number)=>void;page?:number;pageSize?:number;total?:number;serverSide?:boolean;onFilter?:(filters:Record<string,string>)=>void;views?:TableView[];onSaveView?:(view:TableView)=>void;onExport?:()=>void;renderExpanded?:(row:T)=>React.ReactNode}){
 const[filters,setFilters]=useState<Record<string,string>>({});const[expanded,setExpanded]=useState<Set<string>>(new Set());const[detailExpanded,setDetailExpanded]=useState<Set<string>>(new Set());const[widths,setWidths]=useState<Record<string,number>>({});const[order,setOrder]=useState(columns.map(c=>c.key));const[density,setDensity]=useState<'compact'|'normal'|'comfortable'>('normal');const[fullscreen,setFullscreen]=useState(false);const[q,setQ]=useState('');
 const ordered=order.map(k=>columns.find(c=>c.key===k)!).filter(Boolean);
 const filtered=useMemo(()=>serverSide?data:data.filter(row=>{const text=columns.map(c=>String(c.value?.(row)??'')).join(' ').toLowerCase();if(q&&!text.includes(q.toLowerCase()))return false;return Object.entries(filters).every(([k,v])=>!v||String(columns.find(c=>c.key===k)?.value?.(row)??'').toLowerCase().includes(v.toLowerCase()))}),[data,filters,q,columns,serverSide]);
 const totalRows=total??filtered.length;const pages=Math.max(1,Math.ceil(totalRows/pageSize));const shown=serverSide?filtered:filtered.slice((page-1)*pageSize,page*pageSize);
 const setFilter=(k:string,v:string)=>{const next={...filters,[k]:v};setFilters(next);onFilter?.(next)};
 const resize=(key:string,startX:number,startW:number)=>{const move=(e:MouseEvent)=>setWidths(w=>({...w,[key]:Math.max(70,startW+e.clientX-startX)}));const up=()=>{removeEventListener('mousemove',move);removeEventListener('mouseup',up)};addEventListener('mousemove',move);addEventListener('mouseup',up)};
 const moveCol=(key:string,dir:-1|1)=>setOrder(o=>{const a=[...o],i=a.indexOf(key),j=i+dir;if(j<0||j>=a.length)return a;[a[i],a[j]]=[a[j],a[i]];return a});
 const renderRow=(row:T,depth=0):React.ReactNode=>{const id=rowKey(row),kids=childrenOf?.(row)||[],isOpen=expanded.has(id),detail=detailExpanded.has(id);return <React.Fragment key={id}><tr>{ordered.map((c,i)=><td key={c.key} className={cx(c.sticky&&`is-sticky-${c.sticky}`)} style={{width:widths[c.key]||c.width,minWidth:c.minWidth||90,left:c.sticky==='left'?0:undefined,right:c.sticky==='right'?0:undefined}}>{i===0&&<span style={{display:'inline-block',width:depth*16}}/>}{i===0&&kids.length>0&&<button className="ui-adt__tree" onClick={()=>setExpanded(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}>{isOpen?'−':'+'}</button>}{i===0&&renderExpanded&&<button className="ui-adt__detailbtn" onClick={()=>setDetailExpanded(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}>›</button>}{c.editable?<input className="ui-adt__cellinput" defaultValue={String(c.value?.(row)??'')} onBlur={e=>onChangeCell?.(row,c.key,e.target.value)}/>:c.accessor?.(row)??String(c.value?.(row)??'')}</td>)}</tr>{detail&&renderExpanded&&<tr className="ui-adt__expanded"><td colSpan={ordered.length}>{renderExpanded(row)}</td></tr>}{isOpen&&kids.map(k=>renderRow(k,depth+1))}</React.Fragment>};
 return <div className={cx('ui-adt',`ui-adt--${density}`,fullscreen&&'is-fullscreen')}><div className="ui-adt__toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm trong bảng..."/><div className="ui-adt__views"><select onChange={e=>{const v=views.find(x=>x.id===e.target.value);if(v){setFilters(v.filters);if(v.density)setDensity(v.density)}}}><option value="">Saved views</option>{views.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><button onClick={()=>onSaveView?.({id:String(Date.now()),name:'View mới',filters,density})}>Lưu view</button></div><select value={density} onChange={e=>setDensity(e.target.value as typeof density)}><option value="compact">Compact</option><option value="normal">Normal</option><option value="comfortable">Comfortable</option></select><button onClick={onExport}>Export</button><button onClick={()=>setFullscreen(v=>!v)}>{fullscreen?'Thu nhỏ':'Fullscreen'}</button></div><div className="ui-adt__wrap"><table><thead><tr>{ordered.map(c=><th key={c.key} className={cx(c.sticky&&`is-sticky-${c.sticky}`)} style={{width:widths[c.key]||c.width,minWidth:c.minWidth||90,left:c.sticky==='left'?0:undefined,right:c.sticky==='right'?0:undefined}}><div><span>{c.header}</span><span className="ui-adt__colactions"><button onClick={()=>moveCol(c.key,-1)}>‹</button><button onClick={()=>moveCol(c.key,1)}>›</button></span></div><i onMouseDown={e=>resize(c.key,e.clientX,(e.currentTarget.parentElement?.getBoundingClientRect().width||120))}/></th>)}</tr><tr className="ui-adt__filters">{ordered.map(c=><th key={c.key}><input value={filters[c.key]||''} onChange={e=>setFilter(c.key,e.target.value)} placeholder="Lọc..."/></th>)}</tr></thead><tbody>{shown.map(r=>renderRow(r))}</tbody></table></div><div className="ui-adt__footer"><span>{totalRows} bản ghi · trang {page}/{pages}</span><div><button disabled={page<=1} onClick={()=>onPageChange?.(page-1)}>‹</button><button disabled={page>=pages} onClick={()=>onPageChange?.(page+1)}>›</button></div></div></div>
}
