import React,{useEffect,useMemo,useRef,useState} from 'react';
import {cx} from '../../utils/cx';
import './navigation-plus.scss';

export type CommandItem={id:string;label:string;description?:string;shortcut?:string;group?:string;icon?:React.ReactNode;onSelect?:()=>void};
export function CommandPalette({items,open,onClose,placeholder='Tìm trang, component, action...'}:{items:CommandItem[];open:boolean;onClose:()=>void;placeholder?:string}){const[q,setQ]=useState('');const[index,setIndex]=useState(0);const filtered=useMemo(()=>items.filter(x=>`${x.label} ${x.description||''} ${x.group||''}`.toLowerCase().includes(q.toLowerCase())),[items,q]);useEffect(()=>{if(open){setQ('');setIndex(0)}},[open]);if(!open)return null;return <div className="ui-command-backdrop" onMouseDown={onClose}><div className="ui-command" onMouseDown={e=>e.stopPropagation()}><div className="ui-command__search"><span>⌕</span><input autoFocus value={q} onChange={e=>{setQ(e.target.value);setIndex(0)}} placeholder={placeholder} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setIndex(i=>Math.min(filtered.length-1,i+1))}if(e.key==='ArrowUp'){e.preventDefault();setIndex(i=>Math.max(0,i-1))}if(e.key==='Enter'){filtered[index]?.onSelect?.();onClose()}if(e.key==='Escape')onClose()}}/><kbd>Esc</kbd></div><div className="ui-command__list">{filtered.map((x,i)=><button key={x.id} type="button" className={i===index?'is-active':''} onMouseEnter={()=>setIndex(i)} onClick={()=>{x.onSelect?.();onClose()}}><span className="ui-command__icon">{x.icon||'⌘'}</span><span><strong>{x.label}</strong>{x.description&&<small>{x.description}</small>}</span>{x.shortcut&&<kbd>{x.shortcut}</kbd>}</button>)}{!filtered.length&&<div className="ui-command__empty">Không tìm thấy kết quả</div>}</div></div></div>}
export function useCommandPaletteShortcut(onOpen:()=>void,key='k'){useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()===key){e.preventDefault();onOpen()}};addEventListener('keydown',fn);return()=>removeEventListener('keydown',fn)},[onOpen,key])}

export type TreeNode={id:string;label:React.ReactNode;icon?:React.ReactNode;children?:TreeNode[];disabled?:boolean};
export function TreeView({nodes,value,onChange,multiple=false,defaultExpanded=[]}:{nodes:TreeNode[];value?:string|string[];onChange?:(v:string|string[])=>void;multiple?:boolean;defaultExpanded?:string[]}){const[expanded,setExpanded]=useState(new Set(defaultExpanded));const selected=Array.isArray(value)?value:value?[value]:[];const choose=(id:string)=>onChange?.(multiple?(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]):id);const render=(list:TreeNode[],depth=0):React.ReactNode=>list.map(n=><div key={n.id}><div className={cx('ui-tree__row',selected.includes(n.id)&&'is-selected',n.disabled&&'is-disabled')} style={{paddingLeft:8+depth*18}}>{n.children?.length?<button type="button" onClick={()=>setExpanded(s=>{const x=new Set(s);x.has(n.id)?x.delete(n.id):x.add(n.id);return x})}>{expanded.has(n.id)?'▾':'▸'}</button>:<i/>}<button type="button" disabled={n.disabled} onClick={()=>choose(n.id)}>{n.icon}<span>{n.label}</span></button></div>{n.children&&expanded.has(n.id)&&render(n.children,depth+1)}</div>);return <div className="ui-tree">{render(nodes)}</div>}

export type NavItem={id:string;label:React.ReactNode;icon?:React.ReactNode;href?:string;children?:NavItem[];badge?:React.ReactNode};
export function NestedNav({items,activeId,onChange}:{items:NavItem[];activeId?:string;onChange?:(id:string)=>void}){const[open,setOpen]=useState<Set<string>>(new Set());return <nav className="ui-nested-nav">{items.map(item=><div key={item.id}><button type="button" className={activeId===item.id?'is-active':''} onClick={()=>{if(item.children?.length)setOpen(s=>{const n=new Set(s);n.has(item.id)?n.delete(item.id):n.add(item.id);return n});else onChange?.(item.id)}}>{item.icon}<span>{item.label}</span>{item.badge&&<b>{item.badge}</b>}{item.children?.length&&<i>{open.has(item.id)?'⌃':'⌄'}</i>}</button>{item.children&&open.has(item.id)&&<div className="ui-nested-nav__children">{item.children.map(child=><button type="button" key={child.id} className={activeId===child.id?'is-active':''} onClick={()=>onChange?.(child.id)}>{child.icon}<span>{child.label}</span>{child.badge&&<b>{child.badge}</b>}</button>)}</div>}</div>)}</nav>}
export function HorizontalNav({items,activeId,onChange}:{items:NavItem[];activeId?:string;onChange?:(id:string)=>void}){return <nav className="ui-horizontal-nav">{items.map(x=><button type="button" key={x.id} className={activeId===x.id?'is-active':''} onClick={()=>onChange?.(x.id)}>{x.icon}{x.label}{x.badge&&<b>{x.badge}</b>}</button>)}</nav>}

export function SplitPane({first,second,initial=38,min=20,max=75,direction='horizontal'}:{first:React.ReactNode;second:React.ReactNode;initial?:number;min?:number;max?:number;direction?:'horizontal'|'vertical'}){const[size,setSize]=useState(initial);const ref=useRef<HTMLDivElement>(null);const start=(e:React.MouseEvent)=>{e.preventDefault();const move=(ev:MouseEvent)=>{const r=ref.current?.getBoundingClientRect();if(!r)return;const pct=direction==='horizontal'?(ev.clientX-r.left)/r.width*100:(ev.clientY-r.top)/r.height*100;setSize(Math.max(min,Math.min(max,pct)))};const up=()=>{removeEventListener('mousemove',move);removeEventListener('mouseup',up)};addEventListener('mousemove',move);addEventListener('mouseup',up)};return <div ref={ref} className={cx('ui-split',`ui-split--${direction}`)}><div style={direction==='horizontal'?{width:`${size}%`}:{height:`${size}%`}}>{first}</div><button type="button" className="ui-split__handle" onMouseDown={start}/><div>{second}</div></div>}
export function StickyActionFooter({children,summary}:{children:React.ReactNode;summary?:React.ReactNode}){return <div className="ui-sticky-actions"><div>{summary}</div><div>{children}</div></div>}
export function FloatingActionBar({children,position='bottom-center'}:{children:React.ReactNode;position?:'bottom-center'|'bottom-right'}){return <div className={cx('ui-floating-actions',`ui-floating-actions--${position}`)}>{children}</div>}
