import React,{useEffect,useMemo,useRef,useState} from 'react';
import './media.scss';

export type MediaItem={id:string;name:string;url:string;size?:string;status?:'uploading'|'success'|'error';progress?:number};
export function ImageUploader({value=[],onChange,max=8,accept='image/*'}:{value?:MediaItem[];onChange?:(v:MediaItem[])=>void;max?:number;accept?:string}){const input=useRef<HTMLInputElement>(null);const add=(files:File[])=>{const next=files.slice(0,Math.max(0,max-value.length)).map((f,i)=>({id:`img-${Date.now()}-${i}`,name:f.name,url:URL.createObjectURL(f),size:`${Math.max(1,Math.round(f.size/1024))} KB`,status:'success' as const}));onChange?.([...value,...next])};const move=(from:number,to:number)=>{const arr=[...value];const[x]=arr.splice(from,1);arr.splice(to,0,x);onChange?.(arr)};return <div className="ui-image-uploader"><input ref={input} hidden type="file" multiple accept={accept} onChange={e=>{add(Array.from(e.target.files||[]));e.currentTarget.value=''}}/><div className="ui-image-uploader__grid">{value.map((item,i)=><div className="ui-image-uploader__item" key={item.id} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>move(Number(e.dataTransfer.getData('text/plain')),i)}><img src={item.url} alt={item.name}/><div><span>{i===0?'Ảnh bìa':item.name}</span><button type="button" onClick={()=>onChange?.(value.filter(x=>x.id!==item.id))}>×</button></div>{item.status==='uploading'&&<i style={{width:`${item.progress||0}%`}}/>}</div>)}{value.length<max&&<button type="button" className="ui-image-uploader__add" onClick={()=>input.current?.click()}><b>＋</b><span>Thêm ảnh</span><small>{value.length}/{max}</small></button>}</div><small className="ui-media-hint">Kéo thả để sắp xếp · ảnh đầu tiên là ảnh bìa</small></div>}

export function UploadList({items,onRetry,onRemove}:{items:MediaItem[];onRetry?:(id:string)=>void;onRemove?:(id:string)=>void}){return <div className="ui-upload-list">{items.map(x=><div key={x.id} className={`is-${x.status||'success'}`}><span className="ui-upload-list__icon">{x.status==='error'?'!':'↗'}</span><div><strong>{x.name}</strong><small>{x.size||''}</small>{x.status==='uploading'&&<span className="ui-upload-list__bar"><i style={{width:`${x.progress||0}%`}}/></span>}</div><div>{x.status==='error'&&<button type="button" onClick={()=>onRetry?.(x.id)}>Thử lại</button>}<button type="button" onClick={()=>onRemove?.(x.id)}>×</button></div></div>)}</div>}

export function ImageCropper({src,aspect=1,onChange,width=600}:{src:string;aspect?:number;onChange?:(blob:Blob)=>void;width?:number}){const[zoom,setZoom]=useState(1);const[x,setX]=useState(0);const[y,setY]=useState(0);const canvas=useRef<HTMLCanvasElement>(null);const image=useRef<HTMLImageElement|null>(null);useEffect(()=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{image.current=img;draw()};img.src=src},[src]);const draw=()=>{const c=canvas.current,img=image.current;if(!c||!img)return;const ctx=c.getContext('2d');if(!ctx)return;c.width=width;c.height=Math.round(width/aspect);ctx.clearRect(0,0,c.width,c.height);const scale=Math.max(c.width/img.width,c.height/img.height)*zoom;const w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(c.width-w)/2+x,(c.height-h)/2+y,w,h)};useEffect(draw,[zoom,x,y,aspect,width]);const exportCrop=()=>canvas.current?.toBlob(b=>b&&onChange?.(b),'image/jpeg',.92);return <div className="ui-cropper"><canvas ref={canvas}/><div className="ui-cropper__controls"><label>Zoom<input type="range" min="1" max="3" step="0.01" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><label>X<input type="range" min="-200" max="200" value={x} onChange={e=>setX(Number(e.target.value))}/></label><label>Y<input type="range" min="-200" max="200" value={y} onChange={e=>setY(Number(e.target.value))}/></label><button type="button" onClick={exportCrop}>Áp dụng crop</button></div></div>}

export function MediaManager({items,onSelect,selectedId}:{items:MediaItem[];onSelect?:(item:MediaItem)=>void;selectedId?:string}){const[q,setQ]=useState('');const filtered=useMemo(()=>items.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())),[items,q]);return <div className="ui-media-manager"><div className="ui-media-manager__top"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm file..."/><span>{filtered.length} files</span></div><div className="ui-media-manager__grid">{filtered.map(x=><button type="button" key={x.id} className={selectedId===x.id?'is-selected':''} onClick={()=>onSelect?.(x)}><img src={x.url} alt={x.name}/><span>{x.name}</span><small>{x.size}</small></button>)}</div></div>}

export function LightboxGallery({items,startIndex=0,open,onClose}:{items:MediaItem[];startIndex?:number;open:boolean;onClose:()=>void}){const[index,setIndex]=useState(startIndex);useEffect(()=>setIndex(startIndex),[startIndex,open]);if(!open||!items.length)return null;const item=items[index];return <div className="ui-lightbox" onClick={onClose}><button type="button" className="ui-lightbox__close" onClick={onClose}>×</button><button type="button" onClick={e=>{e.stopPropagation();setIndex((index-1+items.length)%items.length)}}>‹</button><figure onClick={e=>e.stopPropagation()}><img src={item.url} alt={item.name}/><figcaption>{item.name} · {index+1}/{items.length}</figcaption></figure><button type="button" onClick={e=>{e.stopPropagation();setIndex((index+1)%items.length)}}>›</button></div>}
