import React,{useEffect,useRef,useState} from 'react';
import {cx} from '../../utils/cx';
import './overlay-plus.scss';

export function Popover({trigger,children,open:controlled,onOpenChange,align='start'}:{trigger:React.ReactNode;children:React.ReactNode;open?:boolean;onOpenChange?:(v:boolean)=>void;align?:'start'|'center'|'end'}){const[inner,setInner]=useState(false);const open=controlled??inner;const set=(v:boolean)=>{if(controlled===undefined)setInner(v);onOpenChange?.(v)};const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!open)return;const fn=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node))set(false)};addEventListener('mousedown',fn);return()=>removeEventListener('mousedown',fn)},[open]);return <div className="ui-popover" ref={ref}><span onClick={()=>set(!open)}>{trigger}</span>{open&&<div className={cx('ui-popover__content',`is-${align}`)}>{children}</div>}</div>}
export type MenuItem={id:string;label:React.ReactNode;icon?:React.ReactNode;danger?:boolean;disabled?:boolean;separatorBefore?:boolean;children?:MenuItem[];onSelect?:()=>void};
export function ContextMenu({children,items}:{children:React.ReactNode;items:MenuItem[]}){const[pos,setPos]=useState<{x:number;y:number}|null>(null);useEffect(()=>{if(!pos)return;const close=()=>setPos(null);addEventListener('mousedown',close);addEventListener('scroll',close,true);return()=>{removeEventListener('mousedown',close);removeEventListener('scroll',close,true)}},[pos]);return <><div onContextMenu={e=>{e.preventDefault();setPos({x:e.clientX,y:e.clientY})}}>{children}</div>{pos&&<div className="ui-context-menu" style={{left:pos.x,top:pos.y}} onMouseDown={e=>e.stopPropagation()}><MenuList items={items} close={()=>setPos(null)}/></div>}</>}
function MenuList({items,close}:{items:MenuItem[];close:()=>void}){return <div className="ui-menu-list">{items.map(x=><React.Fragment key={x.id}>{x.separatorBefore&&<hr/>}<div className="ui-menu-list__row"><button type="button" className={x.danger?'is-danger':''} disabled={x.disabled} onClick={()=>{if(x.children?.length)return;x.onSelect?.();close()}}>{x.icon}<span>{x.label}</span>{x.children?.length&&<b>›</b>}</button>{x.children?.length&&<div className="ui-menu-list__submenu"><MenuList items={x.children} close={close}/></div>}</div></React.Fragment>)}</div>}
export function Menu({items,trigger}:{items:MenuItem[];trigger:React.ReactNode}){return <Popover trigger={trigger} align="end"><MenuList items={items} close={()=>{}}/></Popover>}

export function Sheet({open,onClose,title,children,side='right',width=420,footer}:{open:boolean;onClose:()=>void;title?:React.ReactNode;children:React.ReactNode;side?:'left'|'right';width?:number|string;footer?:React.ReactNode}){if(!open)return null;return <div className="ui-sheet-layer"><div className="ui-sheet-layer__backdrop" onClick={onClose}/><section className={cx('ui-sheet',`ui-sheet--${side}`)} style={{width}}><header><strong>{title}</strong><button type="button" onClick={onClose}>×</button></header><div className="ui-sheet__body">{children}</div>{footer&&<footer>{footer}</footer>}</section></div>}
export function BottomSheet({open,onClose,title,children,footer}:{open:boolean;onClose:()=>void;title?:React.ReactNode;children:React.ReactNode;footer?:React.ReactNode}){if(!open)return null;return <div className="ui-bottom-sheet-layer"><div onClick={onClose}/><section className="ui-bottom-sheet"><i/><header><strong>{title}</strong><button type="button" onClick={onClose}>×</button></header><div className="ui-bottom-sheet__body">{children}</div>{footer&&<footer>{footer}</footer>}</section></div>}
export function HoverCard({trigger,children,delay=160}:{trigger:React.ReactNode;children:React.ReactNode;delay?:number}){const[open,setOpen]=useState(false);const timer=useRef<number|undefined>(undefined);const enter=()=>{clearTimeout(timer.current);timer.current=window.setTimeout(()=>setOpen(true),delay)};const leave=()=>{clearTimeout(timer.current);timer.current=window.setTimeout(()=>setOpen(false),80)};return <span className="ui-hovercard" onMouseEnter={enter} onMouseLeave={leave}>{trigger}{open&&<span className="ui-hovercard__content">{children}</span>}</span>}
export type NotificationItem={id:string;title:string;description?:string;time?:string;read?:boolean;icon?:React.ReactNode;action?:React.ReactNode};
export function NotificationCenter({items,onMarkRead,onMarkAllRead,title='Thông báo'}:{items:NotificationItem[];onMarkRead?:(id:string)=>void;onMarkAllRead?:()=>void;title?:React.ReactNode}){const unread=items.filter(x=>!x.read).length;return <div className="ui-notification-center"><header><div><strong>{title}</strong>{unread>0&&<b>{unread}</b>}</div><button type="button" onClick={onMarkAllRead}>Đánh dấu đã đọc</button></header><div className="ui-notification-center__list">{items.map(x=><button type="button" key={x.id} className={!x.read?'is-unread':''} onClick={()=>onMarkRead?.(x.id)}><span className="ui-notification-center__icon">{x.icon||'•'}</span><span><strong>{x.title}</strong>{x.description&&<small>{x.description}</small>}{x.action&&<em>{x.action}</em>}</span><time>{x.time}</time></button>)}</div></div>}
