import React,{useMemo,useState} from 'react';
import {Field} from '../Field/Field';
import './advanced-input.scss';

export function ColorPicker({label,hint,value='#206bc4',onChange,presets=['#206bc4','#7c3aed','#db2777','#dc2626','#ea580c','#16a34a','#0891b2','#111827']}:{label?:React.ReactNode;hint?:React.ReactNode;value?:string;onChange?:(v:string)=>void;presets?:string[]}){return <Field label={label} hint={hint}><div className="ui-color-picker"><div className="ui-color-picker__input"><input type="color" value={value} onChange={e=>onChange?.(e.target.value)}/><input value={value} onChange={e=>onChange?.(e.target.value)} /></div><div className="ui-color-picker__presets">{presets.map(c=><button type="button" key={c} style={{background:c}} className={value.toLowerCase()===c.toLowerCase()?'is-active':''} onClick={()=>onChange?.(c)} aria-label={c}/>)}</div></div></Field>}
export function PinInput({length=6,value='',onChange,label,hint,type='text'}:{length?:number;value?:string;onChange?:(v:string)=>void;label?:React.ReactNode;hint?:React.ReactNode;type?:'text'|'password'}){const vals=Array.from({length},(_,i)=>value[i]||'');return <Field label={label} hint={hint}><div className="ui-pin">{vals.map((v,i)=><input key={i} inputMode="numeric" type={type} maxLength={1} value={v} onChange={e=>{const ch=e.target.value.replace(/\D/g,'').slice(-1);const next=value.split('');next[i]=ch;onChange?.(next.join('').slice(0,length));if(ch)(e.currentTarget.nextElementSibling as HTMLInputElement|null)?.focus()}} onKeyDown={e=>{if(e.key==='Backspace'&&!v)(e.currentTarget.previousElementSibling as HTMLInputElement|null)?.focus()}}/>)}</div></Field>}
export function Rating({value=0,onChange,max=5,label,hint,readOnly=false}:{value?:number;onChange?:(v:number)=>void;max?:number;label?:React.ReactNode;hint?:React.ReactNode;readOnly?:boolean}){return <Field label={label} hint={hint}><div className="ui-rating" aria-label={`${value}/${max}`}>{Array.from({length:max},(_,i)=><button key={i} type="button" disabled={readOnly} className={i<value?'is-active':''} onClick={()=>onChange?.(i+1)}>★</button>)}</div></Field>}
const digits=(v:string)=>v.replace(/[^0-9.-]/g,'');
export function CurrencyInput({label,hint,value='',onChange,currency='VND',locale='vi-VN'}:{label?:React.ReactNode;hint?:React.ReactNode;value?:number|string;onChange?:(v:number)=>void;currency?:string;locale?:string}){const[focus,setFocus]=useState(false);const n=Number(digits(String(value)))||0;const shown=focus?String(value):new Intl.NumberFormat(locale,{style:'currency',currency,maximumFractionDigits:currency==='VND'?0:2}).format(n);return <Field label={label} hint={hint}><input className="ui-advanced-input" value={shown} onFocus={()=>setFocus(true)} onBlur={()=>setFocus(false)} onChange={e=>onChange?.(Number(digits(e.target.value))||0)}/></Field>}
export function PercentageInput({label,hint,value=0,onChange,min=0,max=100}:{label?:React.ReactNode;hint?:React.ReactNode;value?:number;onChange?:(v:number)=>void;min?:number;max?:number}){return <Field label={label} hint={hint}><div className="ui-affix-input"><input type="number" min={min} max={max} value={value} onChange={e=>onChange?.(Math.min(max,Math.max(min,Number(e.target.value))))}/><span>%</span></div></Field>}
export function MaskedInput({label,hint,value='',onChange,mask='9999 9999 9999',placeholder}:{label?:React.ReactNode;hint?:React.ReactNode;value?:string;onChange?:(v:string)=>void;mask?:string;placeholder?:string}){const apply=(raw:string)=>{const src=raw.replace(/\D/g,'');let i=0,out='';for(const m of mask){if(m==='9'){if(i>=src.length)break;out+=src[i++]}else if(i>0)out+=m}return out};return <Field label={label} hint={hint}><input className="ui-advanced-input" value={value} placeholder={placeholder||mask.replace(/9/g,'_')} onChange={e=>onChange?.(apply(e.target.value))}/></Field>}
export function DualRangeSlider({label,hint,min=0,max=100,step=1,value=[20,80],onChange,formatValue=(v)=>String(v)}:{label?:React.ReactNode;hint?:React.ReactNode;min?:number;max?:number;step?:number;value?:[number,number];onChange?:(v:[number,number])=>void;formatValue?:(v:number)=>string}){const[a,b]=value;const p1=(a-min)/(max-min)*100,p2=(b-min)/(max-min)*100;return <Field label={label} hint={hint}><div className="ui-dual-range"><div className="ui-dual-range__values"><span>{formatValue(a)}</span><span>{formatValue(b)}</span></div><div className="ui-dual-range__track" style={{background:`linear-gradient(to right,var(--ui-surface-3) 0 ${p1}%,var(--ui-primary) ${p1}% ${p2}%,var(--ui-surface-3) ${p2}% 100%)`}}><input type="range" min={min} max={max} step={step} value={a} onChange={e=>onChange?.([Math.min(Number(e.target.value),b-step),b])}/><input type="range" min={min} max={max} step={step} value={b} onChange={e=>onChange?.([a,Math.max(Number(e.target.value),a+step)])}/></div></div></Field>}
export function NumberStepper({label,hint,value=0,onChange,min=-Infinity,max=Infinity,step=1}:{label?:React.ReactNode;hint?:React.ReactNode;value?:number;onChange?:(v:number)=>void;min?:number;max?:number;step?:number}){const set=(n:number)=>onChange?.(Math.min(max,Math.max(min,n)));return <Field label={label} hint={hint}><div className="ui-number-stepper"><button type="button" onClick={()=>set(value-step)}>−</button><input type="number" value={value} onChange={e=>set(Number(e.target.value))}/><button type="button" onClick={()=>set(value+step)}>+</button></div></Field>}
export function PasswordStrength({value}:{value:string}){const score=useMemo(()=>[value.length>=8,/[A-Z]/.test(value),/[0-9]/.test(value),/[^A-Za-z0-9]/.test(value)].filter(Boolean).length,[value]);const labels=['Rất yếu','Yếu','Khá','Mạnh','Rất mạnh'];return <div className="ui-password-strength"><div>{[0,1,2,3].map(i=><i key={i} className={i<score?'is-active':''}/>)}</div><span>{labels[score]}</span></div>}
