import React from 'react';
import './visualization.scss';

const points=(values:number[],w=160,h=48)=>{if(!values.length)return'';const min=Math.min(...values),max=Math.max(...values),range=max-min||1;return values.map((v,i)=>`${(i/(values.length-1||1))*w},${h-((v-min)/range)*h}`).join(' ')};
export function Sparkline({values,width=160,height=48,fill=false}:{values:number[];width?:number;height?:number;fill?:boolean}){const p=points(values,width,height);return <svg className="ui-sparkline" viewBox={`0 0 ${width} ${height}`} role="img">{fill&&<polygon points={`0,${height} ${p} ${width},${height}`} className="ui-sparkline__fill"/>}<polyline points={p} fill="none" className="ui-sparkline__line"/></svg>}
export function KPITrend({label,value,delta,values,tone='primary'}:{label:string;value:React.ReactNode;delta?:string;values:number[];tone?:'primary'|'success'|'danger'|'warning'}){return <div className={`ui-kpi-trend is-${tone}`}><div><span>{label}</span><strong>{value}</strong>{delta&&<small>{delta}</small>}</div><Sparkline values={values} fill/></div>}
export function ProgressRing({value,size=80,stroke=8,label}:{value:number;size?:number;stroke?:number;label?:React.ReactNode}){const r=(size-stroke)/2,c=2*Math.PI*r,d=Math.max(0,Math.min(100,value))/100*c;return <div className="ui-progress-ring" style={{width:size,height:size}}><svg viewBox={`0 0 ${size} ${size}`}><circle cx={size/2} cy={size/2} r={r} className="ui-progress-ring__bg" strokeWidth={stroke}/><circle cx={size/2} cy={size/2} r={r} className="ui-progress-ring__value" strokeWidth={stroke} strokeDasharray={`${d} ${c-d}`} strokeDashoffset={c*.25}/></svg><div><strong>{value}%</strong>{label&&<span>{label}</span>}</div></div>}
export function Gauge({value,min=0,max=100,label}:{value:number;min?:number;max?:number;label?:React.ReactNode}){const pct=Math.max(0,Math.min(1,(value-min)/(max-min||1)));const a=-90+pct*180;return <div className="ui-gauge"><div className="ui-gauge__arc"><i style={{transform:`rotate(${a}deg)`}}/></div><strong>{value}</strong>{label&&<span>{label}</span>}</div>}
export function MiniBarChart({values,labels}:{values:number[];labels?:string[]}){const max=Math.max(...values,1);return <div className="ui-minibar">{values.map((v,i)=><div key={i}><i style={{height:`${v/max*100}%`}}/><span>{labels?.[i]||''}</span></div>)}</div>}
export function FunnelChart({items}:{items:{label:string;value:number}[]}){const max=Math.max(...items.map(x=>x.value),1);return <div className="ui-funnel">{items.map(x=><div key={x.label} style={{width:`${Math.max(24,x.value/max*100)}%`}}><span>{x.label}</span><strong>{x.value}</strong></div>)}</div>}
export function Heatmap({values,rows,cols,format=(v)=>String(v)}:{values:number[][];rows?:string[];cols?:string[];format?:(v:number)=>string}){const flat=values.flat();const max=Math.max(...flat,1),min=Math.min(...flat,0);return <div className="ui-heatmap"><div className="ui-heatmap__cols"><i/>{(cols||values[0]?.map((_,i)=>String(i+1))||[]).map(c=><span key={c}>{c}</span>)}</div>{values.map((row,r)=><div className="ui-heatmap__row" key={r}><span>{rows?.[r]||String(r+1)}</span>{row.map((v,c)=>{const p=(v-min)/(max-min||1);return <i key={c} title={format(v)} style={{background:`color-mix(in srgb,var(--ui-primary) ${Math.round(8+p*82)}%,var(--ui-surface))`}}/>})}</div>)}</div>}
