import {useState} from 'react';
import {
  ThemeProvider,Button,Card,MultiSelect,Combobox,CreatableSelect,Cascader,TimePicker,DateTimePicker,MonthPicker,YearPicker,WeekPicker,DateRangePreset,DualCalendarRange,
  ColorPicker,PinInput,Rating,CurrencyInput,PercentageInput,MaskedInput,DualRangeSlider,NumberStepper,PasswordStrength,
  ImageUploader,AvatarUploader,CoverSelector,UploadList,MediaManager,SortableList,type MediaItem,
  AdvancedDataTable,type AdvancedColumn,CommandPalette,TreeView,NestedNav,HorizontalNav,SplitPane,StickyActionFooter,
  Popover,ContextMenu,Sheet,BottomSheet,HoverCard,NotificationCenter,ChartFrame,Sparkline,KPITrend,ProgressRing,Gauge,MiniBarChart,FunnelChart,Heatmap,
  ProductVariantEditor,SKUMatrix,InventoryEditor,VoucherRuleBuilder,BannerUploader,ProductPicker,CategoryTreePicker,CustomerPicker,OrderStatusTimeline,PaymentStatus,FulfillmentStatus,
  ClipboardField,Kbd,CodeBlock,VirtualList,Collapse,Truncate,RelativeTime,Countdown,QRCodeViewer,BarcodeViewer,type VariantOption,type VariantRow,type Rule
} from '@my/ui';
import './advanced-demo.scss';

const svg=(a:string,b:string,text:string)=>`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 480"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><rect width="640" height="480" fill="url(#g)"/><circle cx="320" cy="185" r="92" fill="white" opacity=".58"/><rect x="205" y="300" width="230" height="74" rx="32" fill="white" opacity=".72"/><text x="320" y="430" text-anchor="middle" font-family="Arial" font-size="28" fill="#334155">${text}</text></svg>`)}`;
const mediaSeed:MediaItem[]=[{id:'1',name:'look-01.jpg',url:svg('#dbeafe','#f5d0fe','Look 01'),size:'328 KB'},{id:'2',name:'look-02.jpg',url:svg('#dcfce7','#fef3c7','Look 02'),size:'292 KB'},{id:'3',name:'look-03.jpg',url:svg('#fee2e2','#e0e7ff','Look 03'),size:'412 KB'}];
const products=[{id:'p1',name:'Áo cardigan dáng ngắn',sku:'SR-1001',price:389000,stock:18,status:'Đang bán'},{id:'p2',name:'Áo zip cổ bẻ',sku:'SR-1002',price:419000,stock:7,status:'Sắp hết'},{id:'p3',name:'Chân váy xếp ly',sku:'SR-1003',price:329000,stock:0,status:'Hết hàng'}];
const cols:AdvancedColumn<(typeof products)[number]>[]=[{key:'name',header:'Sản phẩm',value:r=>r.name,sticky:'left',minWidth:190},{key:'sku',header:'SKU',value:r=>r.sku,editable:true},{key:'price',header:'Giá',value:r=>r.price,editable:true},{key:'stock',header:'Tồn',value:r=>r.stock,editable:true},{key:'status',header:'Trạng thái',value:r=>r.status,sticky:'right'}];
const tree=[{id:'fashion',label:'Thời trang nữ',children:[{id:'tops',label:'Áo',children:[{id:'knit',label:'Áo len'},{id:'jacket',label:'Áo khoác'}]},{id:'skirts',label:'Chân váy'}]},{id:'accessory',label:'Phụ kiện'}];
const pickerItems=products.map(p=>({id:p.id,name:p.name,subtitle:p.sku,meta:`${p.stock} tồn`}));

export default function AdvancedDemo(){
 const[multi,setMulti]=useState<string[]>(['shirt']);const[combo,setCombo]=useState('');const[cascade,setCascade]=useState<string[]>([]);const[color,setColor]=useState('#206bc4');const[pin,setPin]=useState('');const[rating,setRating]=useState(4);const[price,setPrice]=useState(389000);const[pct,setPct]=useState(15);const[phone,setPhone]=useState('');const[dual,setDual]=useState<[number,number]>([20,80]);const[count,setCount]=useState(12);const[password,setPassword]=useState('Sarae@2026');const[range,setRange]=useState({from:'',to:''});
 const[images,setImages]=useState(mediaSeed);const[avatar,setAvatar]=useState<MediaItem|undefined>();const[cover,setCover]=useState('1');const[sortable,setSortable]=useState(['Ảnh chính','Ảnh detail','Ảnh lifestyle']);const[page,setPage]=useState(1);const[command,setCommand]=useState(false);const[sheet,setSheet]=useState(false);const[bottom,setBottom]=useState(false);const[notices,setNotices]=useState([{id:'n1',title:'Có đơn hàng mới',description:'#SR10284 · 589.000 ₫',time:'2 phút',read:false},{id:'n2',title:'SKU sắp hết',description:'Áo zip cổ bẻ còn 7 sản phẩm',time:'15 phút',read:false}]);
 const[variants,setVariants]=useState<VariantOption[]>([{name:'Màu',values:['Trắng','Đen']},{name:'Size',values:['S','M','L']}]);const[skuRows,setSkuRows]=useState<VariantRow[]>([{id:'v1',values:{Màu:'Trắng',Size:'S'},sku:'SR-W-S',price:389000,stock:8},{id:'v2',values:{Màu:'Đen',Size:'M'},sku:'SR-B-M',price:399000,stock:5}]);const[rules,setRules]=useState<Rule[]>([{id:'r1',field:'Tổng đơn hàng',operator:'≥',value:'500000'}]);const[selectedProducts,setSelectedProducts]=useState<string[]>(['p1']);const[selectedCats,setSelectedCats]=useState<string[]>(['knit']);
 const options=[{value:'shirt',label:'Áo nữ'},{value:'dress',label:'Váy & đầm'},{value:'jacket',label:'Áo khoác'},{value:'acc',label:'Phụ kiện'}];
 return <ThemeProvider value={{mode:'light',primary:color,contentWidth:'fluid'}}><div className="advanced-demo"><header className="advanced-demo__hero"><div><span>R Core / Advanced Kit</span><h1>Advanced Components</h1><p>Toàn bộ nhóm component nâng cao cho admin, ecommerce, CMS và dashboard.</p></div><div><Button variant="outline" onClick={()=>location.href='/'}>Demo chính</Button><Button variant="outline" onClick={()=>location.href='/chat.html'}>Chat</Button><Button onClick={()=>setCommand(true)}>Command <Kbd>Ctrl K</Kbd></Button></div></header>
 <DemoSection title="Advanced Select" desc="MultiSelect, searchable combobox, creatable select và cascader."><div className="demo-grid"><MultiSelect label="MultiSelect" options={options} value={multi} onChange={setMulti}/><Combobox label="Combobox" options={options} value={combo} onChange={setCombo}/><CreatableSelect label="Creatable" options={options} value={combo} onChange={setCombo}/><Cascader label="Danh mục nhiều cấp" options={tree.map(x=>({value:x.id,label:String(x.label),children:x.children?.map(y=>({value:y.id,label:String(y.label),children:y.children?.map(z=>({value:z.id,label:String(z.label)}))}))}))} value={cascade} onChange={setCascade}/></div></DemoSection>
 <DemoSection title="Date & Time"><div className="demo-grid"><TimePicker label="Time picker"/><DateTimePicker label="Date time"/><MonthPicker label="Month"/><YearPicker label="Year"/><WeekPicker label="Week"/><DateRangePreset value={range} onChange={setRange}/></div><DualCalendarRange value={range} onChange={setRange}/></DemoSection>
 <DemoSection title="Advanced Inputs"><div className="demo-grid"><ColorPicker label="Color picker" value={color} onChange={setColor}/><PinInput label="OTP / PIN" value={pin} onChange={setPin}/><Rating label="Rating" value={rating} onChange={setRating}/><CurrencyInput label="Currency" value={price} onChange={setPrice}/><PercentageInput label="Percent" value={pct} onChange={setPct}/><MaskedInput label="Phone mask" mask="9999 999 999" value={phone} onChange={setPhone}/><NumberStepper label="Number stepper" value={count} onChange={setCount}/></div><DualRangeSlider label="Khoảng giá" min={0} max={100} value={dual} onChange={setDual} formatValue={v=>`${v}%`}/><div className="password-demo"><input value={password} onChange={e=>setPassword(e.target.value)}/><PasswordStrength value={password}/></div></DemoSection>
 <DemoSection title="Upload & Media"><div className="demo-grid demo-grid--2"><Card title="Image uploader + reorder"><ImageUploader value={images} onChange={setImages}/></Card><Card title="Avatar & cover"><AvatarUploader value={avatar} onChange={setAvatar}/><div className="demo-spacer"/><CoverSelector items={images} value={cover} onChange={setCover}/></Card></div><div className="demo-grid demo-grid--2"><Card title="Upload state"><UploadList items={[{...images[0],status:'uploading',progress:64},{...images[1],status:'success'},{...images[2],status:'error'}]}/></Card><Card title="Sortable list"><SortableList items={sortable} onChange={setSortable} keyOf={x=>x} renderItem={x=><div className="sortable-row">{x}</div>}/></Card></div><MediaManager items={images}/></DemoSection>
 <DemoSection title="Advanced DataTable"><AdvancedDataTable data={products} columns={cols} rowKey={r=>r.id} page={page} pageSize={2} onPageChange={setPage} total={products.length} renderExpanded={r=><div>Chi tiết {r.name} · SKU {r.sku}</div>} onExport={()=>alert('Export adapter')}/></DemoSection>
 <DemoSection title="Navigation & Layout"><div className="demo-grid demo-grid--2"><Card title="Tree view"><TreeView nodes={tree} value={selectedCats} multiple onChange={v=>setSelectedCats(Array.isArray(v)?v:[v])}/></Card><Card title="Nested / horizontal nav"><NestedNav activeId="products" items={[{id:'dashboard',label:'Dashboard'},{id:'catalog',label:'Catalog',children:[{id:'products',label:'Products',badge:24},{id:'categories',label:'Categories'}]},{id:'orders',label:'Orders'}]}/><div className="demo-spacer"/><HorizontalNav activeId="all" items={[{id:'all',label:'Tất cả'},{id:'active',label:'Đang bán',badge:18},{id:'draft',label:'Nháp'}]}/></Card></div><SplitPane first={<div className="pane">Danh sách</div>} second={<div className="pane">Chi tiết</div>}/></DemoSection>
 <DemoSection title="Overlay & Menus"><div className="demo-actions"><Popover trigger={<Button variant="outline">Popover</Button>}><p>Popover content với action/context nhỏ.</p></Popover><ContextMenu items={[{id:'edit',label:'Sửa'},{id:'clone',label:'Nhân bản'},{id:'delete',label:'Xóa',danger:true}]}><Button variant="outline">Right click me</Button></ContextMenu><HoverCard trigger={<Button variant="outline">Hover card</Button>}><strong>Sarae Fashion</strong><p>Hover để xem thông tin nhanh.</p></HoverCard><Button onClick={()=>setSheet(true)}>Sheet</Button><Button onClick={()=>setBottom(true)}>Bottom sheet</Button></div><div className="demo-spacer"/><NotificationCenter items={notices} onMarkRead={id=>setNotices(x=>x.map(n=>n.id===id?{...n,read:true}:n))} onMarkAllRead={()=>setNotices(x=>x.map(n=>({...n,read:true})))}/></DemoSection>
 <DemoSection title="Visualization"><div className="demo-grid demo-grid--3"><KPITrend label="Doanh thu" value="28,4 triệu" delta="+12,8%" values={[12,18,16,24,22,31,38]}/><Card title="Progress ring"><ProgressRing value={74} label="Mục tiêu"/></Card><Card title="Gauge"><Gauge value={68} label="Điểm vận hành"/></Card></div><div className="demo-grid demo-grid--3"><ChartFrame title="Mini bar" height={190}><MiniBarChart values={[12,20,18,32,28,40,35]} labels={['T2','T3','T4','T5','T6','T7','CN']}/></ChartFrame><ChartFrame title="Funnel" height={190}><FunnelChart items={[{label:'View',value:1200},{label:'Cart',value:620},{label:'Checkout',value:320},{label:'Paid',value:184}]}/></ChartFrame><ChartFrame title="Heatmap" height={190}><Heatmap values={[[1,2,5,7,3],[4,8,6,2,1],[2,4,9,7,5]]} rows={['Sáng','Trưa','Tối']} cols={['T2','T3','T4','T5','T6']}/></ChartFrame></div><Card title="Sparkline"><Sparkline values={[3,7,4,10,9,14,12]} fill/></Card></DemoSection>
 <DemoSection title="Ecommerce Patterns"><div className="demo-grid demo-grid--2"><Card title="Product variants"><ProductVariantEditor options={variants} onChange={setVariants}/></Card><Card title="Inventory"><InventoryEditor quantity={18} reserved={4}/><div className="demo-spacer"/><PaymentStatus status="paid"/> <FulfillmentStatus status="processing"/></Card></div><SKUMatrix rows={skuRows} onChange={setSkuRows}/><div className="demo-grid demo-grid--2"><Card title="Voucher rule builder"><VoucherRuleBuilder rules={rules} onChange={setRules}/></Card><Card title="Banner uploader"><BannerUploader value={images.slice(0,1)} onChange={setImages} ratio="16 / 5"/></Card></div><div className="demo-grid demo-grid--3"><Card title="Product picker"><ProductPicker items={pickerItems} value={selectedProducts} onChange={setSelectedProducts} multiple/></Card><Card title="Customer picker"><CustomerPicker items={[{id:'c1',name:'Nguyễn Minh Anh',subtitle:'minhanh@email.com'},{id:'c2',name:'Linh Nguyễn',subtitle:'linh@email.com'}]} value={[]} onChange={()=>{}}/></Card><Card title="Category picker"><CategoryTreePicker nodes={tree} value={selectedCats} onChange={setSelectedCats}/></Card></div><Card title="Order timeline"><OrderStatusTimeline steps={[{id:'1',label:'Đặt hàng',time:'09:20',status:'done'},{id:'2',label:'Đã thanh toán',time:'09:21',status:'done'},{id:'3',label:'Đang đóng gói',description:'Kho Hà Nội',status:'current'},{id:'4',label:'Đang giao',status:'pending'}]}/></Card></DemoSection>
 <DemoSection title="Utilities"><div className="demo-grid demo-grid--3"><Card title="Clipboard & keyboard"><ClipboardField label="Order ID" value="SR-2026-10284"/><p><Kbd>Ctrl</Kbd> + <Kbd>K</Kbd></p></Card><Card title="Relative time / countdown"><p><RelativeTime date={Date.now()-12*60*1000}/></p><Countdown to={Date.now()+3600_000}/></Card><Card title="QR & Barcode"><div className="codes"><QRCodeViewer value="https://sarae.vn/orders/SR-10284" size={110}/><BarcodeViewer value="SR102840026" height={48}/></div></Card></div><CodeBlock language="tsx" code={'<ProductPicker items={products} multiple />'}/><div className="demo-grid demo-grid--2"><Card title="Virtual list"><VirtualList items={Array.from({length:10000},(_,i)=>`Row ${i+1}`)} height={260} renderItem={x=><div className="virtual-row">{x}</div>}/></Card><Card title="Collapse & truncate"><Collapse title="Thông tin nâng cao"><p>Nội dung collapse.</p></Collapse><div className="demo-spacer"/><Truncate lines={2}>Một đoạn mô tả dài dùng cho sản phẩm, bài viết hoặc bảng dữ liệu. Component hỗ trợ rút gọn nội dung theo số dòng và mở rộng khi người dùng cần xem toàn bộ nội dung chi tiết.</Truncate></Card></div></DemoSection>
 <StickyActionFooter summary={<span>Advanced kit · ready for feature pages</span>}><Button variant="outline" onClick={()=>location.href='/'}>Về demo chính</Button><Button onClick={()=>setCommand(true)}>Mở command</Button></StickyActionFooter>
 <CommandPalette open={command} onClose={()=>setCommand(false)} items={[{id:'forms',label:'Forms & inputs',description:'Data entry components'},{id:'chat',label:'Chat & Messaging',description:'Mở demo chat',onSelect:()=>location.href='/chat.html'},{id:'home',label:'Demo chính',onSelect:()=>location.href='/'}]}/><Sheet open={sheet} onClose={()=>setSheet(false)} title="Product detail"><p>Side sheet cho create/edit/detail nhanh mà không rời context hiện tại.</p></Sheet><BottomSheet open={bottom} onClose={()=>setBottom(false)} title="Mobile actions"><p>Bottom sheet tối ưu thao tác mobile.</p></BottomSheet>
 </div></ThemeProvider>
}
function DemoSection({title,desc,children}:{title:string;desc?:string;children:React.ReactNode}){return <section className="demo-section"><div className="demo-section__head"><div><span>Component group</span><h2>{title}</h2>{desc&&<p>{desc}</p>}</div></div><div className="demo-section__body">{children}</div></section>}
