import React,{useMemo,useState} from 'react';
import {Field} from '../Field/Field';
import './datetime.scss';

type Common={label?:React.ReactNode;hint?:React.ReactNode;disabled?:boolean};
export function TimePicker({label,hint,value,onChange,step=300,disabled}:Common&{value?:string;onChange?:(v:string)=>void;step?:number}){return <Field label={label} hint={hint}><input className="ui-datetime" type="time" value={value} step={step} disabled={disabled} onChange={e=>onChange?.(e.target.value)}/></Field>}
export function DateTimePicker({label,hint,value,onChange,disabled}:Common&{value?:string;onChange?:(v:string)=>void}){return <Field label={label} hint={hint}><input className="ui-datetime" type="datetime-local" value={value} disabled={disabled} onChange={e=>onChange?.(e.target.value)}/></Field>}
export function MonthPicker({label,hint,value,onChange,disabled}:Common&{value?:string;onChange?:(v:string)=>void}){return <Field label={label} hint={hint}><input className="ui-datetime" type="month" value={value} disabled={disabled} onChange={e=>onChange?.(e.target.value)}/></Field>}
export function WeekPicker({label,hint,value,onChange,disabled}:Common&{value?:string;onChange?:(v:string)=>void}){return <Field label={label} hint={hint}><input className="ui-datetime" type="week" value={value} disabled={disabled} onChange={e=>onChange?.(e.target.value)}/></Field>}
export function YearPicker({label,hint,value,onChange,min=1970,max=2100,disabled}:Common&{value?:number;onChange?:(v:number)=>void;min?:number;max?:number}){const years=useMemo(()=>Array.from({length:max-min+1},(_,i)=>max-i),[min,max]);return <Field label={label} hint={hint}><select className="ui-datetime" value={value||''} disabled={disabled} onChange={e=>onChange?.(Number(e.target.value))}><option value="">Chọn năm</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select></Field>}
export type DatePreset={label:string;from:string;to:string};
const iso=(d:Date)=>d.toISOString().slice(0,10);
export function DateRangePreset({label='Khoảng thời gian',value,onChange,presets}:{label?:React.ReactNode;value?:{from:string;to:string};onChange?:(v:{from:string;to:string})=>void;presets?:DatePreset[]}){
 const today=new Date();const defaults:DatePreset[]=[{label:'Hôm nay',from:iso(today),to:iso(today)},{label:'7 ngày',from:iso(new Date(Date.now()-6*86400000)),to:iso(today)},{label:'30 ngày',from:iso(new Date(Date.now()-29*86400000)),to:iso(today)},{label:'Tháng này',from:iso(new Date(today.getFullYear(),today.getMonth(),1)),to:iso(today)}];const list=presets||defaults;
 return <Field label={label}><div className="ui-date-preset"><div className="ui-date-preset__quick">{list.map(p=><button type="button" key={p.label} onClick={()=>onChange?.({from:p.from,to:p.to})}>{p.label}</button>)}</div><div className="ui-date-preset__inputs"><input type="date" value={value?.from||''} onChange={e=>onChange?.({from:e.target.value,to:value?.to||''})}/><span>→</span><input type="date" value={value?.to||''} onChange={e=>onChange?.({from:value?.from||'',to:e.target.value})}/></div></div></Field>
}
export function DualCalendarRange({label='Date range',value,onChange}: {label?:React.ReactNode;value?:{from:string;to:string};onChange?:(v:{from:string;to:string})=>void}){const[month,setMonth]=useState(new Date());const month2=new Date(month.getFullYear(),month.getMonth()+1,1);const render=(base:Date)=>{const first=new Date(base.getFullYear(),base.getMonth(),1);const start=(first.getDay()+6)%7;const days=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();return <div className="ui-dualcal__month"><strong>{base.toLocaleDateString('vi-VN',{month:'long',year:'numeric'})}</strong><div className="ui-dualcal__week">{['T2','T3','T4','T5','T6','T7','CN'].map(x=><span key={x}>{x}</span>)}</div><div className="ui-dualcal__grid">{Array.from({length:start},(_,i)=><i key={`e${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=new Date(base.getFullYear(),base.getMonth(),i+1);const v=iso(date);const selected=v===value?.from||v===value?.to;const inside=!!value?.from&&!!value?.to&&v>value.from&&v<value.to;return <button type="button" key={v} className={`${selected?'is-selected ':''}${inside?'is-range':''}`} onClick={()=>{if(!value?.from||value.to||v<value.from)onChange?.({from:v,to:''});else onChange?.({from:value.from,to:v})}}>{i+1}</button>})}</div></div>};return <Field label={label}><div className="ui-dualcal"><div className="ui-dualcal__nav"><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><span>{value?.from||'—'} → {value?.to||'—'}</span><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><div className="ui-dualcal__months">{render(month)}{render(month2)}</div></div></Field>}
