import React,{useMemo,useState} from 'react';
import {CurrencyInput,NumberStepper} from '../AdvancedInput/AdvancedInput';
import {TreeView,type TreeNode} from '../NavigationPlus/NavigationPlus';
import {ImageUploader,type MediaItem} from '../Media/Media';
import './ecommerce.scss';

export type VariantOption={name:string;values:string[]};
export type VariantRow={id:string;values:Record<string,string>;sku:string;price:number;stock:number;enabled?:boolean};
export function ProductVariantEditor({options,onChange}:{options:VariantOption[];onChange?:(v:VariantOption[])=>void}){const add=()=>onChange?.([...options,{name:'Thuộc tính',values:['Giá trị']}]);const update=(i:number,next:Partial<VariantOption>)=>onChange?.(options.map((x,n)=>n===i?{...x,...next}:x));return <div className="ui-variant-editor">{options.map((o,i)=><div key={i}><input value={o.name} onChange={e=>update(i,{name:e.target.value})}/><div>{o.values.map((v,j)=><span key={j}><input value={v} onChange={e=>update(i,{values:o.values.map((x,n)=>n===j?e.target.value:x)})}/><button type="button" onClick={()=>update(i,{values:o.values.filter((_,n)=>n!==j)})}>×</button></span>)}<button type="button" onClick={()=>update(i,{values:[...o.values,'']})}>+ Giá trị</button></div></div>)}<button type="button" className="ui-variant-editor__add" onClick={add}>+ Thêm thuộc tính</button></div>}
export function SKUMatrix({rows,onChange}:{rows:VariantRow[];onChange?:(rows:VariantRow[])=>void}){const patch=(id:string,p:Partial<VariantRow>)=>onChange?.(rows.map(r=>r.id===id?{...r,...p}:r));const keys=Array.from(new Set(rows.flatMap(r=>Object.keys(r.values))));return <div className="ui-sku-matrix"><table><thead><tr>{keys.map(k=><th key={k}>{k}</th>)}<th>SKU</th><th>Giá</th><th>Tồn</th><th>Bán</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{keys.map(k=><td key={k}>{r.values[k]}</td>)}<td><input value={r.sku} onChange={e=>patch(r.id,{sku:e.target.value})}/></td><td><input type="number" value={r.price} onChange={e=>patch(r.id,{price:Number(e.target.value)})}/></td><td><input type="number" value={r.stock} onChange={e=>patch(r.id,{stock:Number(e.target.value)})}/></td><td><input type="checkbox" checked={r.enabled!==false} onChange={e=>patch(r.id,{enabled:e.target.checked})}/></td></tr>)}</tbody></table></div>}
export const PriceInput=CurrencyInput;
export function InventoryEditor({quantity=0,reserved=0,onChange}:{quantity?:number;reserved?:number;onChange?:(q:number)=>void}){return <div className="ui-inventory-editor"><NumberStepper label="Tồn kho thực tế" value={quantity} min={0} onChange={onChange}/><div className="ui-inventory-editor__stats"><span>Đã giữ <strong>{reserved}</strong></span><span>Có thể bán <strong>{Math.max(0,quantity-reserved)}</strong></span></div></div>}

export type Rule={id:string;field:string;operator:string;value:string};
const fields=['Tổng đơn hàng','Số lượng sản phẩm','Danh mục','Khách hàng','Kênh bán'];const operators=['=','≠','>','≥','<','≤','contains'];
export function DiscountConditionBuilder({rules,onChange}:{rules:Rule[];onChange?:(v:Rule[])=>void}){const patch=(id:string,p:Partial<Rule>)=>onChange?.(rules.map(r=>r.id===id?{...r,...p}:r));return <div className="ui-rule-builder">{rules.map((r,i)=><div key={r.id}><b>{i===0?'IF':'AND'}</b><select value={r.field} onChange={e=>patch(r.id,{field:e.target.value})}>{fields.map(x=><option key={x}>{x}</option>)}</select><select value={r.operator} onChange={e=>patch(r.id,{operator:e.target.value})}>{operators.map(x=><option key={x}>{x}</option>)}</select><input value={r.value} onChange={e=>patch(r.id,{value:e.target.value})}/><button type="button" onClick={()=>onChange?.(rules.filter(x=>x.id!==r.id))}>×</button></div>)}<button type="button" onClick={()=>onChange?.([...rules,{id:String(Date.now()),field:fields[0],operator:'≥',value:''}])}>+ Thêm điều kiện</button></div>}
export function VoucherRuleBuilder({rules,onChange,type='discount'}:{rules:Rule[];onChange?:(v:Rule[])=>void;type?:'discount'|'free-shipping'|'gift'}){return <div className="ui-voucher-builder"><div className="ui-voucher-builder__head"><strong>{type==='discount'?'Voucher giảm giá':type==='free-shipping'?'Miễn phí vận chuyển':'Tặng quà'}</strong><span>Thỏa tất cả điều kiện bên dưới</span></div><DiscountConditionBuilder rules={rules} onChange={onChange}/></div>}

export function BannerUploader({value,onChange,ratio='16 / 5',max=1}:{value:MediaItem[];onChange?:(v:MediaItem[])=>void;ratio?:string;max?:number}){return <div className="ui-banner-uploader" style={{'--banner-ratio':ratio} as React.CSSProperties}><ImageUploader value={value} onChange={onChange} max={max}/><small>Tỷ lệ khuyến nghị: {ratio.replace('/',' : ')}</small></div>}

type PickerItem={id:string;name:string;subtitle?:string;image?:string;meta?:React.ReactNode};
function EntityPicker({items,value,onChange,multiple=false,placeholder='Tìm kiếm...'}:{items:PickerItem[];value?:string[];onChange?:(v:string[])=>void;multiple?:boolean;placeholder?:string}){const[q,setQ]=useState('');const selected=value||[];const list=useMemo(()=>items.filter(x=>`${x.name} ${x.subtitle||''}`.toLowerCase().includes(q.toLowerCase())),[items,q]);const pick=(id:string)=>onChange?.(multiple?(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]):[id]);return <div className="ui-entity-picker"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={placeholder}/><div>{list.map(x=><button type="button" key={x.id} className={selected.includes(x.id)?'is-selected':''} onClick={()=>pick(x.id)}>{x.image?<img src={x.image} alt=""/>:<i>{x.name[0]}</i>}<span><strong>{x.name}</strong>{x.subtitle&&<small>{x.subtitle}</small>}</span>{x.meta&&<em>{x.meta}</em>}{selected.includes(x.id)&&<b>✓</b>}</button>)}</div></div>}
export const ProductPicker=(props:React.ComponentProps<typeof EntityPicker>)=><EntityPicker {...props} placeholder="Tìm sản phẩm..."/>;
export const CustomerPicker=(props:React.ComponentProps<typeof EntityPicker>)=><EntityPicker {...props} placeholder="Tìm khách hàng..."/>;
export const CollectionPicker=(props:React.ComponentProps<typeof EntityPicker>)=><EntityPicker {...props} placeholder="Tìm bộ sưu tập..."/>;
export function CategoryTreePicker({nodes,value,onChange,multiple=true}:{nodes:TreeNode[];value?:string[];onChange?:(v:string[])=>void;multiple?:boolean}){return <div className="ui-category-picker"><TreeView nodes={nodes} value={value||[]} multiple={multiple} defaultExpanded={nodes.slice(0,2).map(x=>x.id)} onChange={v=>onChange?.(Array.isArray(v)?v:[v])}/></div>}

export type OrderStep={id:string;label:string;time?:string;description?:string;status:'done'|'current'|'pending'|'error'};
export function OrderStatusTimeline({steps}:{steps:OrderStep[]}){return <div className="ui-order-timeline">{steps.map((s,i)=><div key={s.id} className={`is-${s.status}`}><span>{s.status==='done'?'✓':s.status==='error'?'!':i+1}</span><div><strong>{s.label}</strong>{s.description&&<p>{s.description}</p>}<small>{s.time}</small></div></div>)}</div>}
const statusTone:Record<string,string>={paid:'success',pending:'warning',failed:'danger',refunded:'muted',fulfilled:'success',processing:'warning',cancelled:'danger',partial:'primary'};
export function PaymentStatus({status}:{status:'paid'|'pending'|'failed'|'refunded'}){return <span className={`ui-commerce-status is-${statusTone[status]}`}>{status==='paid'?'Đã thanh toán':status==='pending'?'Chờ thanh toán':status==='failed'?'Thanh toán lỗi':'Đã hoàn tiền'}</span>}
export function FulfillmentStatus({status}:{status:'fulfilled'|'processing'|'cancelled'|'partial'}){return <span className={`ui-commerce-status is-${statusTone[status]}`}>{status==='fulfilled'?'Đã hoàn tất':status==='processing'?'Đang xử lý':status==='cancelled'?'Đã hủy':'Một phần'}</span>}
