import React,{useEffect,useMemo,useRef,useState} from 'react';
import QRCodeLib from 'qrcode';
import JsBarcode from 'jsbarcode';
import './utility.scss';

export function CopyButton({value,label='Copy',copiedLabel='Đã copy'}:{value:string;label?:React.ReactNode;copiedLabel?:React.ReactNode}){const[copied,setCopied]=useState(false);return <button type="button" className="ui-copy-button" onClick={async()=>{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1200)}}>{copied?copiedLabel:label}</button>}
export function ClipboardField({value,label}:{value:string;label?:React.ReactNode}){return <div className="ui-clipboard-field">{label&&<span>{label}</span>}<div><code>{value}</code><CopyButton value={value} label="⧉" copiedLabel="✓"/></div></div>}
export function Kbd({children}:{children:React.ReactNode}){return <kbd className="ui-kbd">{children}</kbd>}
export function CodeBlock({code,language='text',copy=true}:{code:string;language?:string;copy?:boolean}){return <div className="ui-codeblock"><header><span>{language}</span>{copy&&<CopyButton value={code}/>}</header><pre><code>{code}</code></pre></div>}
export function ScrollArea({children,height=320}:{children:React.ReactNode;height?:number|string}){return <div className="ui-scroll-area" style={{height}}>{children}</div>}
export function InfiniteScroll({children,onLoadMore,hasMore=true,loading=false,rootMargin='160px'}:{children:React.ReactNode;onLoadMore:()=>void;hasMore?:boolean;loading?:boolean;rootMargin?:string}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current;if(!el||!hasMore)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting&&!loading)onLoadMore()},{rootMargin});o.observe(el);return()=>o.disconnect()},[onLoadMore,hasMore,loading,rootMargin]);return <>{children}<div className="ui-infinite-sentinel" ref={ref}>{loading?'Đang tải...':hasMore?'':'Đã hết dữ liệu'}</div></>}
export function VirtualList<T>({items,height=360,rowHeight=44,renderItem,overscan=5}:{items:T[];height?:number;rowHeight?:number;renderItem:(item:T,index:number)=>React.ReactNode;overscan?:number}){const[top,setTop]=useState(0);const start=Math.max(0,Math.floor(top/rowHeight)-overscan);const count=Math.ceil(height/rowHeight)+overscan*2;const end=Math.min(items.length,start+count);return <div className="ui-virtual-list" style={{height}} onScroll={e=>setTop(e.currentTarget.scrollTop)}><div style={{height:items.length*rowHeight,position:'relative'}}>{items.slice(start,end).map((item,i)=><div key={start+i} style={{position:'absolute',left:0,right:0,top:(start+i)*rowHeight,height:rowHeight}}>{renderItem(item,start+i)}</div>)}</div></div>}
export function Collapse({title,children,defaultOpen=false}:{title:React.ReactNode;children:React.ReactNode;defaultOpen?:boolean}){const[open,setOpen]=useState(defaultOpen);return <div className="ui-collapse"><button type="button" onClick={()=>setOpen(v=>!v)}><span>{title}</span><i>{open?'−':'+'}</i></button>{open&&<div>{children}</div>}</div>}
export function Truncate({children,lines=2,expandLabel='Xem thêm',collapseLabel='Thu gọn'}:{children:React.ReactNode;lines?:number;expandLabel?:string;collapseLabel?:string}){const[open,setOpen]=useState(false);return <div className="ui-truncate"><div style={open?undefined:{display:'-webkit-box',WebkitLineClamp:lines,WebkitBoxOrient:'vertical',overflow:'hidden'}}>{children}</div><button type="button" onClick={()=>setOpen(v=>!v)}>{open?collapseLabel:expandLabel}</button></div>}
export function RelativeTime({date,now=Date.now()}:{date:Date|string|number;now?:number}){const d=new Date(date).getTime(),diff=Math.round((d-now)/1000),abs=Math.abs(diff);let value:number,unit:Intl.RelativeTimeFormatUnit;if(abs<60){value=diff;unit='second'}else if(abs<3600){value=Math.round(diff/60);unit='minute'}else if(abs<86400){value=Math.round(diff/3600);unit='hour'}else{value=Math.round(diff/86400);unit='day'}return <time dateTime={new Date(d).toISOString()}>{new Intl.RelativeTimeFormat('vi',{numeric:'auto'}).format(value,unit)}</time>}
export function Countdown({to,onComplete}:{to:Date|string|number;onComplete?:()=>void}){const[left,setLeft]=useState(Math.max(0,new Date(to).getTime()-Date.now()));useEffect(()=>{const id=setInterval(()=>{const n=Math.max(0,new Date(to).getTime()-Date.now());setLeft(n);if(n===0){clearInterval(id);onComplete?.()}},1000);return()=>clearInterval(id)},[to,onComplete]);const s=Math.floor(left/1000),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;return <span className="ui-countdown">{d>0&&<><b>{d}</b><small>ngày</small></>}<b>{String(h).padStart(2,'0')}</b>:<b>{String(m).padStart(2,'0')}</b>:<b>{String(sec).padStart(2,'0')}</b></span>}
export function QRCodeViewer({value,size=180,margin=1}:{value:string;size?:number;margin?:number}){const[url,setUrl]=useState('');useEffect(()=>{QRCodeLib.toDataURL(value,{width:size,margin}).then(setUrl)},[value,size,margin]);return <div className="ui-code-viewer">{url?<img src={url} width={size} height={size} alt="QR code"/>:<span>...</span>}</div>}
export function BarcodeViewer({value,format='CODE128',height=70,displayValue=true}:{value:string;format?:string;height?:number;displayValue?:boolean}){const ref=useRef<SVGSVGElement>(null);useEffect(()=>{if(ref.current)JsBarcode(ref.current,value,{format,height,displayValue,margin:0,background:'transparent',lineColor:'currentColor'})},[value,format,height,displayValue]);return <div className="ui-barcode"><svg ref={ref}/></div>}
